# Generated by Django 3.1.4 on 2021-07-03 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, default='', null=True)),
                ('images', models.ImageField(blank=True, default='', null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='media')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='files')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=80)),
                ('Description', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('file', models.FileField(default='', upload_to='certificates')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('text', models.TextField(default='')),
                ('designation', models.CharField(default='', max_length=500)),
                ('images', models.ImageField(default='', upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1500)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('venue', models.CharField(default='', max_length=5000)),
                ('eventdate', models.DateField()),
                ('time', models.TimeField(blank=True, default='', null=True)),
            ],
            options={
                'ordering': ['-eventdate', 'time'],
            },
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='')),
                ('answer', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=1000)),
                ('subject', models.CharField(default='', max_length=1500)),
                ('message', models.TextField(default='')),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='', upload_to='gallery')),
                ('caption', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='guideline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='img_slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='', upload_to='gallery')),
                ('caption', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='', max_length=1500, null=True)),
                ('title', models.CharField(default='', max_length=1500)),
                ('category', models.CharField(choices=[('synopsis', 'Synopsis '), ('nonsynopsis', 'Non-Synopsis ')], default='', max_length=150)),
                ('subcategory', models.CharField(choices=[('categorya', 'Category A'), ('categoryb', 'Category B'), ('categoryc', 'Category C'), ('categorybc', 'CategoryB/C')], default='', max_length=150)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='projects')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='sop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=80)),
                ('Description', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('file', models.FileField(default='', upload_to='sops')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('designation', models.CharField(default='', max_length=1000)),
                ('contact', models.CharField(blank=True, default='', max_length=1500, null=True)),
            ],
        ),
    ]
